name: adds comments on issues

on:
  issues:
    types: [opened]
    
jobs: 
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
    - name: dump context
      run: echo '${{ to Json(github.event) }}' | jq
      shell: bash
